services:
  clickhouse:
    image: clickhouse/clickhouse-server
    user: "101:101"
    hostname: clickhouse
    volumes:
      - ${PWD}/devel/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/devel/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "9000:9000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/?query=SELECT%201 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
